/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-05-20 04:05:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class StudentIdea_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Sign Up Form by Colorlib</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Icon -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"material-design-iconic-font.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"signup-content\">\r\n");
      out.write("                <div class=\"signup-img\">\r\n");
      out.write("                    <img src=\"signup-img.jpg\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"signup-form\">\r\n");
      out.write("                    <form  action=\"xyz9\" method=\"POST\" class=\"register-form\" id=\"register-form\">\r\n");
      out.write("                        <h2>student idea form</h2>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"sid\">Research Id:</label>\r\n");
      out.write("                            <input type=\"text\" name=\"txtid\" id=\"txtid\" required/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"sname\">Student Name :</label>\r\n");
      out.write("                            <input type=\"text\" name=\"txtName\" id=\"txtName\" required/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-radio\">\r\n");
      out.write("                            <label for=\"gender\" class=\"radio-label\">Gender :</label>\r\n");
      out.write("                            <div class=\"form-radio-item\">\r\n");
      out.write("                                <input type=\"radio\" name=\"txtGender\" value=\"male\" checked>\r\n");
      out.write("                                <label for=\"male\">Male</label>\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-radio-item\">\r\n");
      out.write("                                <input type=\"radio\" name=\"txtGender\" value=\"female\">\r\n");
      out.write("                                <label for=\"female\">Female</label>\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"city\">Company :</label>\r\n");
      out.write("                                <div class=\"form-select\">\r\n");
      out.write("                                    <select name=\"txtCom\" id=\"txtCom\">\r\n");
      out.write("                                        <option value=\"\"></option>\r\n");
      out.write("                                        <option value=\"SISCO\">SISCO Lab</option>\r\n");
      out.write("                                        <option value=\"WSO2\">WSO2</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <span class=\"select-icon\"><i class=\"zmdi zmdi-chevron-down\"></i></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"birth_date\">Date :</label>\r\n");
      out.write("                            <input type=\"text\" name=\"txtDate\" id=\"txtDate\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"course\">Course :</label>\r\n");
      out.write("                            <div class=\"form-select\">\r\n");
      out.write("                                <select name=\"txtCourse\" id=\"txtCourse\">\r\n");
      out.write("                                    <option value=\"\"></option>\r\n");
      out.write("                                    <option value=\"computer\">Computer Science</option>\r\n");
      out.write("                                    <option value=\"desiger\">MIS</option>\r\n");
      out.write("                                    <option value=\"marketing\">Software Engineering</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <span class=\"select-icon\"><i class=\"zmdi zmdi-chevron-down\"></i></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"email\">Email ID :</label>\r\n");
      out.write("                            <input type=\"email\" name=\"txtMail\" id=\"txtMail\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"email\">idea :</label>\r\n");
      out.write("                            <textarea name=\"txtIdea\" id=\"txtIdea\" rows=\"8\" cols=\"71\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-submit\">\r\n");
      out.write("                            <input type=\"submit\" value=\"Reset All\" class=\"submit\" name=\"btnReset\" id=\"reset\" />\r\n");
      out.write("                            <input type=\"submit\" value=\"Submit Form\" class=\"submit\" name=\"btnSubmit\" id=\"submit\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS -->\r\n");
      out.write("    <script src=\"jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"main.js\"></script>\r\n");
      out.write("</body><!-- This templates was made by Colorlib (https://colorlib.com) -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
