/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-05-11 15:43:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UniIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("     <title>Known - Education HTML Template</title>\r\n");
      out.write("<!-- \r\n");
      out.write("\r\n");
      out.write("Known Template \r\n");
      out.write("\r\n");
      out.write("https://templatemo.com/tm-516-known\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("     <meta charset=\"UTF-8\">\r\n");
      out.write("     <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("     <meta name=\"description\" content=\"\">\r\n");
      out.write("     <meta name=\"keywords\" content=\"\">\r\n");
      out.write("     <meta name=\"author\" content=\"\">\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"bootstrap8.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"font-awesome8.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"owl8.carousel.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"owl8.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("     <!-- MAIN CSS -->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"templatemo-style8.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"top\" data-spy=\"scroll\" data-target=\".navbar-collapse\" data-offset=\"50\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <section id=\"home\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"owl-carousel owl-theme home-slider\">\r\n");
      out.write("                         <div class=\"item item-first\">\r\n");
      out.write("                              <div class=\"caption\">\r\n");
      out.write("                                   <div class=\"container\">\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("                                             <h1>NSBM Green University</h1>\r\n");
      out.write("                                       \r\n");
      out.write("                                           <img src=\"NSBM.jpg\" width=\"800px\" hight=\"800px\"/>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- FEATURE -->\r\n");
      out.write("     <section id=\"feature\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("                         <div class=\"feature-thumb\">\r\n");
      out.write("                              <span>01</span>\r\n");
      out.write("                              <h3><a href=\"Events.jsp\">Upload Events</a></h3>\r\n");
      out.write("                              <p>Known is free education HTML Bootstrap Template. You can download and use this for your website.</p>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("                         <div class=\"feature-thumb\">\r\n");
      out.write("                              <span>02</span>\r\n");
      out.write("                              <h3><a href=\"StudentIdea.jsp\">Post Student Ideas</a></h3>\r\n");
      out.write("                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing eiusmod tempor incididunt ut labore et dolore magna.</p>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("                         <div class=\"feature-thumb\">\r\n");
      out.write("                              <span>03</span>\r\n");
      out.write("                              <h3><a href=\"ResearchProblem.jsp\">Upload Research Problem</a></h3>\r\n");
      out.write("                              <p>templatemo provides a wide variety of free Bootstrap Templates for you. Please tell your friends about us. Thank you.</p>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- ABOUT -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("     <!-- TEAM -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- Courses -->\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- CONTACT -->\r\n");
      out.write("     <\r\n");
      out.write("\r\n");
      out.write("     <!-- FOOTER -->\r\n");
      out.write("     <footer id=\"footer\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("                         <div class=\"footer-info\">\r\n");
      out.write("                              <div class=\"section-title\">\r\n");
      out.write("                                   <h2>Headquarter</h2>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <address>\r\n");
      out.write("                                   <p>1800 dapibus a tortor pretium,<br> Integer nisl dui, ABC 12000</p>\r\n");
      out.write("                              </address>\r\n");
      out.write("\r\n");
      out.write("                              <ul class=\"social-icon\">\r\n");
      out.write("                                   <li><a href=\"#\" class=\"fa fa-facebook-square\" attr=\"facebook icon\"></a></li>\r\n");
      out.write("                                   <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("                                   <li><a href=\"#\" class=\"fa fa-instagram\"></a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("\r\n");
      out.write("                              <div class=\"copyright-text\"> \r\n");
      out.write("                                   <p>Copyright &copy; 2019 Company Name</p>\r\n");
      out.write("                                   \r\n");
      out.write("                                   <p>Design: TemplateMo</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("                         <div class=\"footer-info\">\r\n");
      out.write("                              <div class=\"section-title\">\r\n");
      out.write("                                   <h2>Contact Info</h2>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <address>\r\n");
      out.write("                                   <p>+65 2244 1100, +66 1800 1100</p>\r\n");
      out.write("                                   <p><a href=\"mailto:youremail.co\">hello@youremail.co</a></p>\r\n");
      out.write("                              </address>\r\n");
      out.write("\r\n");
      out.write("                              <div class=\"footer_menu\">\r\n");
      out.write("                                   <h2>Quick Links</h2>\r\n");
      out.write("                                   <ul>\r\n");
      out.write("                                        <li><a href=\"#\">Career</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Investor</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Terms & Conditions</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Refund Policy</a></li>\r\n");
      out.write("                                   </ul>\r\n");
      out.write("                              </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-12\">\r\n");
      out.write("                         <div class=\"footer-info newsletter-form\">\r\n");
      out.write("                              <div class=\"section-title\">\r\n");
      out.write("                                   <h2>Newsletter Signup</h2>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div>\r\n");
      out.write("                                   <div class=\"form-group\">\r\n");
      out.write("                                        <form action=\"#\" method=\"get\">\r\n");
      out.write("                                             <input type=\"email\" class=\"form-control\" placeholder=\"Enter your email\" name=\"email\" id=\"email\" required=\"\">\r\n");
      out.write("                                             <input type=\"submit\" class=\"form-control\" name=\"submit\" id=\"form-submit\" value=\"Send me\">\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                        <span><sup>*</sup> Please note - we do not spam your email.</span>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("               </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- SCRIPTS -->\r\n");
      out.write("     <script src=\"jquery8.js\"></script>\r\n");
      out.write("     <script src=\"bootstrap8.min.js\"></script>\r\n");
      out.write("     <script src=\"owl8.carousel.min.js\"></script>\r\n");
      out.write("     <script src=\"smoothscroll8.js\"></script>\r\n");
      out.write("     <script src=\"custom8.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
